In [33]:
import numpy as np
import pandas as pd
import scipy
#from scipy.cluster.vq import kmeans, vq
from sklearn.preprocessing import normalize
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [42]:
data = pd.read_csv('lines.csv')
data['index'] = data.index
data.head()

filename  ink_volume  height  words_ratio  index
0  lines/page0_block0_line0.png    0.319284      16     0.016166      0
1  lines/page0_block0_line1.png    0.350393      17     0.016949      1
2  lines/page0_block0_line2.png    0.305815      17     0.017291      2
3  lines/page0_block0_line3.png    0.370192      17     0.016827      3
4  lines/page0_block0_line4.png    0.300601      17     0.022364      4

In [43]:
features = ['ink_volume', 'height', 'words_ratio']
X = data.loc[:, features].values

In [53]:
X[:10]

array([[  3.19284065e-01,   1.60000000e+01,   1.61662818e-02],
       [  3.50393265e-01,   1.70000000e+01,   1.69491525e-02],
       [  3.05814545e-01,   1.70000000e+01,   1.72910663e-02],
       [  3.70192308e-01,   1.70000000e+01,   1.68269231e-02],
       [  3.00601391e-01,   1.70000000e+01,   2.23642173e-02],
       [  3.56412729e-01,   1.70000000e+01,   2.29508197e-02],
       [  3.65625000e-01,   1.60000000e+01,   1.25000000e-02],
       [  2.57357680e-01,   1.90000000e+01,   2.04081633e-02],
       [  2.39195348e-01,   2.10000000e+01,   2.31023102e-02],
       [  2.50165344e-01,   2.10000000e+01,   2.08333333e-02]])

In [54]:
normalize(X[:10])

array([[  1.99512718e-02,   9.99800443e-01,   1.01019098e-03],
       [  2.06069815e-02,   9.99787157e-01,   9.96796766e-04],
       [  1.79861716e-02,   9.99837719e-01,   1.01695649e-03],
       [  2.17708462e-02,   9.99762497e-01,   9.89583920e-04],
       [  1.76796557e-02,   9.99842837e-01,   1.31533544e-03],
       [  2.09608294e-02,   9.99779387e-01,   1.34975038e-03],
       [  2.28455914e-02,   9.99738700e-01,   7.81045860e-04],
       [  1.35438908e-02,   9.99907700e-01,   1.07401472e-03],
       [  1.13895090e-02,   9.99934532e-01,   1.10003799e-03],
       [  1.19117844e-02,   9.99928560e-01,   9.91992619e-04]])

In [55]:
#centroids, a = kmeans(X, 3)
#idx, b = vq(X, centroids)
kmeans = KMeans(n_clusters=3, random_state=0).fit(normalize(X))

In [56]:
kmeans.labels_

array([1, 1, 2, 1, 2, 1, 1, 2, 0, 0, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2,
       2, 2, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2,
       0, 0, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2, 0, 0, 2, 2, 1, 0, 2, 0, 0, 2, 2,
       2, 0, 0, 0, 2, 2, 2, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 2,
       0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 2, 1, 2, 2, 0, 2, 2, 0,
       1, 0, 2, 2, 0, 0, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 1, 1, 1, 2, 0, 0, 0,
       0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 2, 0, 0, 2, 2, 2], dtype=int32)

In [58]:
kmeans.cluster_centers_

array([[  1.21396443e-02,   9.99925467e-01,   1.00484905e-03],
       [  2.16073336e-02,   9.99764751e-01,   1.19409333e-03],
       [  1.45677660e-02,   9.99892797e-01,   9.79267498e-04]])